[development]
dynaconf_merge = true

[development.server]
log_level = "debug"
reload = true
cors_origins = ["http://localhost:8111"]

[production]
dynaconf_merge = true

[production.server]
log_level = "error"
reload = false

[testing]
dynaconf_merge = true

[testing.server]
cors_origins = ["http://localhost:3000", "http://localhost:4200"]